#端口号
server:
  port: 8088
#数据库的配置信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spider #自己的数据库名称
    username: root
    password: 123456
mybatis:
  #开启驼峰命名法
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  # xml地址
  mapper-locations: classpath:mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com/haoshuai/intelligentcommunity/entity   #自己的实体类地址
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl